name: challenge_swiss
description: Challenge Swiss Medical app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # Internationalization  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  

  # Router
  auto_route: ^9.2.2
 
  # Animation
  animate_do: ^3.3.4
  carousel_slider_plus: ^7.0.1
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # Persistence
  flutter_cache_manager: ^3.4.1 
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_dotenv: ^5.2.1

  # JSON Serialization
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Data Manipulation
  get_it: ^8.0.2

  # UI
  shimmer: ^3.0.0 
  
  # Network
  dio: ^5.7.0
  logger: ^2.4.0
  cached_network_image: ^3.4.1
  
  # System Functions
  path_provider: ^2.0.11

dev_dependencies:
  
  # Code generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7

  # Unit tests
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - .env